### ISSUE TITLE
a READ memory access in pocl?

### ISSUE THREAD

**Issue by Mundi-Xu** [pocl/pocl#1019]
# a READ memory access in pocl(or llvm?)

## VERSION

pocl:  v1.8

hashcat: v6.2.5-38-g8b61f60e8

llvm: llvm-toolchain-13-13.0.1~++20211216073040+87ca22cba2fa

## REPRODUCTION CASE

pocl: `cmake -DWITH_LLVM_CONFIG=llvm-config-13 -DENABLE_ICD=0  -DCMAKE_C_FLAGS="-g" -DCMAKE_CXX_FLAGS="-g" ..`

hashcat: `CFLAGS="-fsanitize=address" make`

` hashcat -b -m 17010` (Need to run `make install` first and use hashcat installed in the **system directory**)

## ASAN INFO

```
root@f1f8747ad674:/work/utils/pocl/build# hashcat -b -m 17010
hashcat (v6.2.5-38-g8b61f60e8) starting in benchmark mode

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

OpenCL API (OpenCL 2.0 pocl 1.8  Linux, Debug+Asserts, RELOC, SPIR, LLVM 13.0.1, SLEEF, LTTNG, POCL_DEBUG) - Platform #1 [The pocl project]
===========================================================================================================================================
* Device #1: pthread-Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz, 127723/255510 MB (32768 MB allocatable), 96MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

----------------------------------------------------------------------------
* Hash-Mode 17010 (GPG (AES-128/AES-256 (SHA-1($pass)))) [Iterations: 65536]
----------------------------------------------------------------------------

AddressSanitizer:DEADLYSIGNAL
=================================================================
==24553==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f8ab804e2f5 bp 0x7f8aa30ce060 sp 0x7f8aa30ce050 T10)
==24553==The signal is caused by a READ memory access.
==24553==Hint: address points to the zero page.
    #0 0x7f8ab804e2f5 in llvm::Value::getType() const /usr/lib/llvm-13/include/llvm/IR/Value.h:256
    #1 0x7f8ab80c3e63 in llvm::IRBuilderBase::CreateLoad(llvm::Value*, llvm::Twine const&) /usr/lib/llvm-13/include/llvm/IR/IRBuilder.h:1682
    #2 0x7f8ab80cae35 in pocl::ParallelRegion::LocalIDXLoad() /work/utils/pocl/lib/llvmopencl/ParallelRegion.cc:656
    #3 0x7f8ab80cd1ff in pocl::ParallelRegion::LocalizeIDLoads() /work/utils/pocl/lib/llvmopencl/ParallelRegion.cc:810
    #4 0x7f8ab80c76af in pocl::ParallelRegion::Create(llvm::SmallPtrSet<llvm::BasicBlock*, 8u> const&, llvm::BasicBlock*, llvm::BasicBlock*) /work/utils/pocl/lib/llvmopencl/ParallelRegion.cc:366
    #5 0x7f8ab80a045e in pocl::Kernel::createParallelRegionBefore(llvm::BasicBlock*) /work/utils/pocl/lib/llvmopencl/Kernel.cc:140
    #6 0x7f8ab80a0af1 in pocl::Kernel::getParallelRegions(llvm::LoopInfo*) /work/utils/pocl/lib/llvmopencl/Kernel.cc:191
    #7 0x7f8ab81277ec in pocl::WorkitemLoops::ProcessFunction(llvm::Function&) /work/utils/pocl/lib/llvmopencl/WorkitemLoops.cc:390
    #8 0x7f8ab8124ad2 in pocl::WorkitemLoops::runOnFunction(llvm::Function&) /work/utils/pocl/lib/llvmopencl/WorkitemLoops.cc:114
    #9 0x7f8aaf6b728f in llvm::FPPassManager::runOnFunction(llvm::Function&) (/lib/x86_64-linux-gnu/libLLVM-13.so.1+0xeca28f)
    #10 0x7f8aaf6bce02 in llvm::FPPassManager::runOnModule(llvm::Module&) (/lib/x86_64-linux-gnu/libLLVM-13.so.1+0xecfe02)
    #11 0x7f8aaf6b7897 in llvm::legacy::PassManagerImpl::run(llvm::Module&) (/lib/x86_64-linux-gnu/libLLVM-13.so.1+0xeca897)
    #12 0x7f8ab818bbc4 in pocl_llvm_generate_workgroup_function_nowrite /work/utils/pocl/lib/CL/pocl_llvm_wg.cc:481
    #13 0x7f8ab802ff76 in llvm_codegen /work/utils/pocl/lib/CL/devices/common.c:134
    #14 0x7f8ab8038d54 in pocl_check_kernel_disk_cache /work/utils/pocl/lib/CL/devices/common.c:921
    #15 0x7f8ab803a24b in pocl_check_kernel_dlhandle_cache /work/utils/pocl/lib/CL/devices/common.c:1044
    #16 0x7f8aab97efec in pocl_pthread_prepare_kernel /work/utils/pocl/lib/CL/devices/pthread/pthread_scheduler.c:353
    #17 0x7f8aab97fe57 in pthread_scheduler_get_work /work/utils/pocl/lib/CL/devices/pthread/pthread_scheduler.c:475
    #18 0x7f8aab98036e in pocl_pthread_driver_thread /work/utils/pocl/lib/CL/devices/pthread/pthread_scheduler.c:530
    #19 0x7f8ac8dec608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
    #20 0x7f8ac8bb1292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/lib/llvm-13/include/llvm/IR/Value.h:256 in llvm::Value::getType() const
Thread T10 created by T0 here:
    #0 0x7f8ac90786d5 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x7f8aab97d157 in pthread_scheduler_init /work/utils/pocl/lib/CL/devices/pthread/pthread_scheduler.c:112
    #2 0x7f8aab97ba71 in pocl_pthread_init /work/utils/pocl/lib/CL/devices/pthread/pthread.c:216
    #3 0x7f8ab802be52 in pocl_init_devices /work/utils/pocl/lib/CL/devices/devices.c:594
    #4 0x7f8ab7f6bb0b in POclGetDeviceIDs /work/utils/pocl/lib/CL/clGetDeviceIDs.c:50
    #5 0x5602cc7933fa  (/usr/local/bin/hashcat+0x12d3fa)

==24553==ABORTING
```

## Additional Info

```
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_WARN_INCOMPATIBLE_POINTER_TYPES
-- Performing Test HAVE_WARN_INCOMPATIBLE_POINTER_TYPES - Success
-- Setting build type to 'Debug' as none was specified.
-- No git and/or not a prerelease -> not adding git commit to version.
-- Host CPU cores: 96
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'hwloc'
--   Found hwloc, version 2.1.0
-- Found Hwloc: hwloc
-- Found hwloc 2.1.0 in :hwloc
-- Hwloc_VERSION 2.1.0
-- Hwloc_LIBRARIES hwloc
-- Hwloc_INCLUDE_DIRS
-- L1D Cacheline size detected: 64
-- Using llvm-config: /usr/bin/llvm-config-13
-- LLVM binaries suffix : -13
-- llvm-config's LLVM_PREFIX is: /usr/lib/llvm-13
-- llvm-config's LLVM_VERSION_FULL is: 13.0.1
-- LLVM_VERSION: 13.0
-- llvm-config's LLVM_CFLAGS is: -I/usr/lib/llvm-13/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- llvm-config's LLVM_CXXFLAGS is: -I/usr/lib/llvm-13/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- llvm-config's LLVM_CPPFLAGS is: -I/usr/lib/llvm-13/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- llvm-config's LLVM_LDFLAGS is: -L/usr/lib/llvm-13/lib
-- llvm-config's LLVM_BINDIR is: /usr/lib/llvm-13/bin
-- llvm-config's LLVM_LIBDIR is: /usr/lib/llvm-13/lib
-- llvm-config's LLVM_INCLUDEDIR is: /usr/lib/llvm-13/include
-- llvm-config's LLVM_SRC_ROOT is: /build/llvm-toolchain-13-13.0.1~++20211216073040+87ca22cba2fa/llvm
-- llvm-config's LLVM_OBJ_ROOT is: /usr/lib/llvm-13
-- llvm-config's LLVM_ALL_TARGETS is: AArch64 AMDGPU ARM AVR BPF Hexagon Lanai Mips MSP430 NVPTX PowerPC RISCV Sparc SystemZ WebAssembly X86 XCore M68k
-- llvm-config's LLVM_HOST_TARGET is: x86_64-pc-linux-gnu
-- llvm-config's LLVM_BUILD_MODE is: RelWithDebInfo
-- llvm-config's LLVM_ASSERTS_BUILD is: OFF
-- llvm-config's LLVM_SYSLIBS is:
-- llvm-config's LLVM_HAS_RTTI is: YES
-- llvm-config's LLVM_LIBS is: -lLLVM-13
-- llvm-config's LLVM_SYSLIBS is:
-- Found clang: /usr/lib/llvm-13/bin/clang-13
-- Found clang++: /usr/bin/clang++-13
-- Found opt: /usr/bin/opt-13
-- Found llc: /usr/bin/llc-13
-- Found llvm-as: /usr/bin/llvm-as-13
-- Found llvm-link: /usr/bin/llvm-link-13
-- Found lli: /usr/bin/lli-13
-- udivmodti4 compiles without extra flags
-- Checking if clang++ works (required by vecmathlib)
-- Checking if LLVM is a DEBUG build
-- DEBUG build
-- Find out LLC target triple (for host x86_64-pc-linux-gnu)
-- Find out LLC host CPU with /usr/bin/llc-13
-- Checking clang -march vs. -mcpu flag
--   Using -march=
-- LLVM link test OK
-- Checking fp16 support
-- FP16 is disabled: 1
-- Looking for fork
-- Looking for fork - found
-- Looking for fsync
-- Looking for fsync - found
-- Looking for sleep
-- Looking for sleep - found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for utime
-- Looking for utime - found
-- Looking for ANNOTATE_HAPPENS_BEFORE
-- Looking for ANNOTATE_HAPPENS_BEFORE - not found
-- Looking for futimens
-- Looking for futimens - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for fdatasync
-- Looking for fdatasync - found
-- Looking for mkdtemp
-- Looking for mkdtemp - found
-- Looking for mkstemps
-- Looking for mkstemps - found
-- Looking for vfork
-- Looking for vfork - found
-- Looking for mkostemps
-- Looking for mkostemps - found
-- Looking for dladdr
-- Looking for dladdr - found
-- Private Datadir Relative path: ../share/pocl
-- Compiler supports IPO: YES
-- Enable Link-Time Optimization (IPO) while building pocl runtime : 1
CMake Warning at CMakeLists.txt:786 (message):
  SPIR support is available but highly experimental; use at your own risk.


-- libdl found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Checking for module 'lttng-ust>=2.7'
--   Found lttng-ust, version 2.11.0
-- Checking for module 'ocl-icd>=1.3'
--   Found ocl-icd, version 2.2.11
-- ICD loader found, but requested build without it
-- Using an ICD loader (cached): 0
-- Run tests with ICD: 0
-- OpenCL.h found, NOT installing our headers
-- Failed to find tcecc or tce-config, disabling TCE
-- TCE support : 0
-- Building the following device drivers: basic pthreads
-- cascadelake SLEEF: 128bit vectors available.
-- cascadelake SLEEF: 128bit hardware FMA available.
-- cascadelake SLEEF: 256bit vectors available.
-- cascadelake SLEEF: 256bit hardware FMA available.
-- cascadelake SLEEF: 512bit vectors available.
-- cascadelake SLEEF: 512bit hardware FMA available.
-- cascadelake SLEEF bc list: /work/utils/pocl/build/lib/kernel/host/cascadelake/c_sleefsp.c.bc;/work/utils/pocl/build/lib/kernel/host/cascadelake/c_sleefdp.c.bc;/work/utils/pocl/build/lib/kernel/host/cascadelake/c_sleef_glue_auto.c.bc;/work/utils/pocl/build/lib/kernel/host/cascadelake/v128_sleefsimdsp.c.bc;/work/utils/pocl/build/lib/kernel/host/cascadelake/v128_sleefsimddp.c.bc;/work/utils/pocl/build/lib/kernel/host/cascadelake/v256_sleefsimdsp.c.bc;/work/utils/pocl/build/lib/kernel/host/cascadelake/v256_sleefsimddp.c.bc;/work/utils/pocl/build/lib/kernel/host/cascadelake/v512_sleefsimdsp.c.bc;/work/utils/pocl/build/lib/kernel/host/cascadelake/v512_sleefsimddp.c.bc
-- cascadelake SLEEF bc: /work/utils/pocl/build/lib/kernel/host/cascadelake/sleef.bc
-- Host Kernel BC for "cascadelake": /work/utils/pocl/build/lib/kernel/host/kernel-x86_64-pc-linux-gnu-cascadelake.bc
-- CPACK_DEBIAN_LIB_PACKAGE_BREAKS
-- CPACK_DEBIAN_LIB_PACKAGE_DEPENDS
-- CPACK_DEBIAN_LIB_PACKAGE_NAME
-- CPACK_DEBIAN_LIB_PACKAGE_RECOMMENDS
-- CPACK_DEBIAN_LIB_PACKAGE_REPLACES
-- OPENCL_LIBS: Threads::Threads;OpenCL;-L/usr/lib/x86_64-linux-gnu;-lhwloc;/usr/lib/llvm-13/lib/libclang-cpp.so;/usr/lib/llvm-13/lib/libLLVM-13.so;-L/usr/lib/x86_64-linux-gnu;-llttng-ust;-ldl;rt;-lm;dl;Threads::Threads
-- OPENCL_CFLAGS:
-- POCLU LINK OPTS: poclu;Threads::Threads;OpenCL;-L/usr/lib/x86_64-linux-gnu;-lhwloc;/usr/lib/llvm-13/lib/libclang-cpp.so;/usr/lib/llvm-13/lib/libLLVM-13.so;-L/usr/lib/x86_64-linux-gnu;-llttng-ust;-ldl;rt;-lm;dl;Threads::Threads;-lm
-- CPACK_DEBIAN_LIB_PACKAGE_BREAKS
-- CPACK_DEBIAN_LIB_PACKAGE_DEPENDS
-- CPACK_DEBIAN_LIB_PACKAGE_NAME
-- CPACK_DEBIAN_LIB_PACKAGE_RECOMMENDS
-- CPACK_DEBIAN_LIB_PACKAGE_REPLACES
-- CPACK_DEBIAN_POCLCC_PACKAGE_DEPENDS
-- CPACK_DEBIAN_POCLCC_PACKAGE_NAME
--
-- *********************** SUMMARY ***************************
--
-- ******* Directories:
--
-- CMAKE_INSTALL_PREFIX: /usr/local
-- POCL_INSTALL_CMAKE_CONFIG_DIR: /usr/local/lib/pocl
-- POCL_INSTALL_ICD_VENDORDIR: /usr/local/etc/OpenCL/vendors
-- POCL_INSTALL_OPENCL_HEADER_DIR: /usr/local/include/CL
-- POCL_INSTALL_PKGCONFIG_DIR: /usr/local/lib/pkgconfig
-- POCL_INSTALL_PRIVATE_DATADIR: /usr/local/share/pocl
-- POCL_INSTALL_PRIVATE_HEADER_DIR: /usr/local/share/pocl/include
-- POCL_INSTALL_PRIVATE_LIBDIR: /usr/local/lib/pocl
-- POCL_INSTALL_PUBLIC_BINDIR: /usr/local/bin
-- POCL_INSTALL_PUBLIC_HEADER_DIR: /usr/local/include
-- POCL_INSTALL_PUBLIC_LIBDIR: /usr/local/lib
--
--
-- ******* LLVM Programs:
--
-- LLVM_CONFIG: /usr/bin/llvm-config-13
-- LLVM_OPT: /usr/bin/opt-13
-- LLVM_LLC: /usr/bin/llc-13
-- LLVM_AS: /usr/bin/llvm-as-13
-- LLVM_LINK: /usr/bin/llvm-link-13
-- LLVM_LLI: /usr/bin/lli-13
-- WITH_LLVM_CONFIG (User preferred llvm-config): /work/utils/pocl/build/llvm-config-13
--
-- ******* Various Flags:
--
-- CL_DISABLE_HALF: 1
-- HAVE_CLOCK_GETTIME: 1
-- HAVE_GLEW:
-- HAVE_LTTNG_UST: 1
-- HOST_AS_FLAGS:
-- HOST_CLANG_FLAGS: --target=x86_64-pc-linux-gnu -D_CL_DISABLE_HALF
-- HOST_LD_FLAGS: -shared
-- HOST_LLC_FLAGS: -relocation-model=pic -mtriple=x86_64-pc-linux-gnu
--
-- LIB_API_VERSION: 2
-- LIB_BUILD_VERSION: 2.8.0
-- ICD_LD_FLAGS: -Wl,-Bsymbolic
-- EXTRA_KERNEL_FLAGS:
-- EXTRA_KERNEL_CXX_FLAGS:
-- EXTRA_KERNEL_CL_FLAGS:
-- EXTRA_KERNEL_C_FLAGS:
-- final KERNEL_CXX_FLAGS: -xc++ -std=c++11 -fno-stack-protector -fPIC
-- final KERNEL_CL_FLAGS: -xcl -fno-stack-protector -fPIC
-- final KERNEL_C_FLAGS: -xc -std=c11 -D__CBUILD__ -fno-math-errno -fno-stack-protector -fPIC
--
-- CLANG_HAS_64B_MATH: ON
-- CLANG_HAS_128B_MATH: ON
-- CLANG_NEEDS_RTLIB: OFF
-- CLANG_MARCH_FLAG: -march=
-- CLANG_TARGET_OPTION: --target=
-- LLVM_VERSION: 13.0
-- LLVM_LIB_IS_SHARED:
-- LLVM_HAS_RTTI: YES
-- LLVM_LIB_MODE: --link-shared
-- LLVM_ASSERTS_BUILD: OFF
-- LLVM_BUILD_MODE: RelWithDebInfo
-- LLVM_CFLAGS: -I/usr/lib/llvm-13/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM_CXXFLAGS: -I/usr/lib/llvm-13/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM_CPPFLAGS: -I/usr/lib/llvm-13/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM_LDFLAGS: -L/usr/lib/llvm-13/lib -Wl,--exclude-libs,libclang-cpp
-- LLVM_LIBDIR: /usr/lib/llvm-13/lib
-- LLVM_INCLUDEDIR: /usr/lib/llvm-13/include
-- LLVM_SRC_ROOT: /build/llvm-toolchain-13-13.0.1~++20211216073040+87ca22cba2fa/llvm
-- LLVM_OBJ_ROOT: /usr/lib/llvm-13
-- LLVM_INCLUDE_DIRS:
-- LLVM_ALL_TARGETS: AArch64 AMDGPU ARM AVR BPF Hexagon Lanai Mips MSP430 NVPTX PowerPC RISCV Sparc SystemZ WebAssembly X86 XCore M68k
-- LLVM_HOST_TARGET: x86_64-pc-linux-gnu
-- LLC_TRIPLE: x86_64-pc-linux-gnu
-- LLC_HOST_CPU: cascadelake
--
-- MAX_EXTENDED_ALIGNMENT: 128
-- OCL_KERNEL_TARGET: x86_64-pc-linux-gnu
-- OCL_KERNEL_TARGET_CPU: cascadelake
-- HOST_DEVICE_ADDRESS_BITS: 64
--
-- ----------- -------------------------------- --------
-- llvm libs libpocl will be linked to (POCL_LLVM_LIBS):
-- /usr/lib/llvm-13/lib/libLLVM-13.so
-- ----------- -------------------------------- --------
-- clang libs libpocl will be linked to (CLANG_LIBFILES):
-- /usr/lib/llvm-13/lib/libclang-cpp.so
-- ----------- -------------------------------- --------
-- system libs libpocl will be linked to (LLVM_SYSLIBS):
--
-- ----------- -------------------------------- --------
-- ******* Enabled features:
--
-- DEVELOPER_MODE: OFF
-- ENABLE_CONFORMANCE: ON
-- ENABLE_IPO: YES
-- ENABLE_ICD: 0
-- ENABLE_TCE: 0
-- ENABLE_TCEMC: 0
-- ENABLE_HSA: OFF
-- ENABLE_CUDA: OFF
-- ENABLE_ASAN (address sanitizer): OFF
-- ENABLE_LSAN (leak sanitizer): OFF
-- ENABLE_TSAN (thread sanitizer): OFF
-- ENABLE_UBSAN (UB sanitizer): OFF
-- ENABLE_POCL_FLOAT_CONVERSION: OFF
-- ENABLE_RELOCATION: ON
-- ENABLE_SLEEF: ON
-- ENABLE_SPIR: ON
-- ENABLE_SPIRV: OFF
-- ENABLE_POCL_BUILDING: ON
-- INSTALL_OPENCL_HEADERS (Install our headers): 0
-- OCL_DRIVERS (Drivers built): basic pthreads
-- OCL_TARGETS (Targets built): host
-- ENABLE_LLVM: ON
-- POCL_ICD_ABSOLUTE_PATH: ON
-- POCL_ASSERTS_BUILD: 1
-- TESTS_USE_ICD: 0
-- Available testsuites: AMD;AMDSDK2.9;AMDSDK3.0;ASL;arrayfire;clBLAS;CLBlast;clFFT;conformance;CloverLeaf;Halide;IntelSVM;opencl-book-samples;OpenCV;Parboil;piglit;PyOpenCL;Rodinia;shoc;VexCL;ViennaCL;Glow
-- Enabled testsuites:
-- Disabled testsuites: AMD;AMDSDK2.9;AMDSDK3.0;ASL;arrayfire;clBLAS;CLBlast;clFFT;conformance;CloverLeaf;Halide;IntelSVM;opencl-book-samples;OpenCV;Parboil;piglit;PyOpenCL;Rodinia;shoc;VexCL;ViennaCL;Glow
-- Testsuites are built from git master: OFF
-- Kernel caching: ON
-- Kernel library CPU variants: native
-- Kernel library distro build: 0
-- Use pocl custom memory allocator: OFF
-- L1d cacheline size: 64
-- Configuring done
-- Generating done
-- Build files have been written to: /work/utils/pocl/build
```

```
LIST OF DEVICES:
0:
  Vendor:   GenuineIntel
    Name:   pthread-Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
 Version:   OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-cascadelake
```

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
