### ISSUE TITLE
Segmentation fault in clGetDeviceIDs on WSL/Ubuntu 21.10+

### ISSUE THREAD

**Issue by Anteru** [pocl/pocl#1024]
I'm not sure who/what is causing this, but this is the observed behavior:

`clGetDeviceIDs` causes a segmentation fault:

```
#0  __vfscanf_internal (s=0x0, format=0x7f2faa0cf929 "%x", argptr=argptr@entry=0x7fffb53c0e00, mode_flags=mode_flags@entry=2) at vfscanf-internal.c:345
#1  0x00007f2faa6a400d in __isoc99_fscanf (stream=<optimized out>, format=<optimized out>) at isoc99_fscanf.c:30
#2  0x00007f2faa06fd42 in ?? () from /lib/x86_64-linux-gnu/libpocl.so.2.6.0
#3  0x00007f2fa3824836 in ?? () from /lib/x86_64-linux-gnu/pocl/libpocl-devices-pthread.so
#4  0x00007f2faa069d76 in ?? () from /lib/x86_64-linux-gnu/libpocl.so.2.6.0
#5  0x00007f2faa045297 in ?? () from /lib/x86_64-linux-gnu/libpocl.so.2.6.0
```

This does not happen with POCL 1.4 in an Ubuntu 20.04 container, but it happens with 1.6.4 and 1.6.5 in Ubuntu 21.10 and Ubuntu 22.04 containers. Repro steps:

```$ docker run --it ubuntu:21.10
root@...:/# apt update
root@...:/# apt install -qq -y pocl-opencl-icd clinfo
root@...:/# clinfo
Number of platforms                               1
  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 1.2 pocl 1.6, None+Asserts, LLVM 9.0.1, RELOC, SLEEF, DISTRO, POCL_DEBUG
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL
Segmentation fault
```

On Ubuntu 20.04 this works just fine. I have no idea if docker, Ubuntu, or POCL is at fault here, but `clGetDeviceIDs` shouldn't be crashing as long as a valid platform ID is passed in. I can reproduce the same issue in my own code, and I do get a platform ID returned from `clGetPlatformIDs` which I pass into `clGetDeviceIDs`. It crashes in this query:
```
clGetDeviceIDs (platform, CL_DEVICE_TYPE_GPU, 0, nullptr,
		&gpuDeviceCount)
```

I also tried to run with `POCL_DEBUG` but it only prints that the SIGFPE handler is installed. Disabling that doesn't change anything. I'd appreciate if there was a workaround or something I could use to make this work given I can't easily update to a newer POCL in the container. Building `pocl` manually from source -- using version 1.8 -- works, so it's something specific to 1.6.x.

**Comment by Devon7** [comment]
Still broken in Debian on VirtualBox:
```
$ uname -a
Linux LX 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
$ cat /etc/debian_version
11.5
$ make clean
⋮
$ make DEBUG=1
⋮
$ gdb ./hashcat
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
⋮
Reading symbols from ./hashcat...
(gdb) run --backend-info
Starting program: /home/devon/dist/hashcat/hashcat --backend-info
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
hashcat (v6.2.6-183-ga82cf950b) starting in backend information mode


Program received signal SIGSEGV, Segmentation fault.
__vfscanf_internal (s=0x0, format=0x7fffe0899929 "%x", argptr=argptr@entry=0x7ffffffed6f0, mode_flags=mode_flags@entry=2) at vfscanf-internal.c:345
345	vfscanf-internal.c: No such file or directory.
(gdb) backtrace
#0  __vfscanf_internal (s=0x0, format=0x7fffe0899929 "%x", argptr=argptr@entry=0x7ffffffed6f0, mode_flags=mode_flags@entry=2) at vfscanf-internal.c:345
#1  0x00007ffff7cd3269 in __isoc99_fscanf (stream=<optimized out>, format=<optimized out>) at isoc99_fscanf.c:30
#2  0x00007fffe0839d92 in ?? () from /lib/x86_64-linux-gnu/libpocl.so.2.6.0
#3  0x00007fffd866f836 in ?? () from /lib/x86_64-linux-gnu/pocl/libpocl-devices-pthread.so
#4  0x00007fffe0833db6 in ?? () from /lib/x86_64-linux-gnu/libpocl.so.2.6.0
#5  0x00007fffe080f277 in ?? () from /lib/x86_64-linux-gnu/libpocl.so.2.6.0
#6  0x00005555555cd705 in hc_clGetDeviceIDs (hashcat_ctx=hashcat_ctx@entry=0x5555556952a0, platform=platform@entry=0x7fffe08bd008, device_type=device_type@entry=4294967295, num_entries=num_entries@entry=128, 
    devices=devices@entry=0x5555556a44e0, num_devices=num_devices@entry=0x7fffffffea44) at src/ext_OpenCL.c:455
#7  0x00005555555ace71 in backend_ctx_init (hashcat_ctx=hashcat_ctx@entry=0x5555556952a0) at src/backend.c:4808
#8  0x000055555555c732 in hashcat_session_init (hashcat_ctx=hashcat_ctx@entry=0x5555556952a0, install_folder=install_folder@entry=0x55555565d1de "/usr/local/bin", 
    shared_folder=shared_folder@entry=0x55555565d1c5 "/usr/local/share/hashcat", argc=argc@entry=2, argv=argv@entry=0x7fffffffec18, comptime=comptime@entry=1671732440) at src/hashcat.c:1287
#9  0x000055555555b80d in main (argc=2, argv=0x7fffffffec18) at src/main.c:1294
(gdb) 
⋮
$ date; git remote -v; git status
Thu 22 Dec 2022 01:17:05 PM EST
origin	https://github.com/hashcat/hashcat.git (fetch)
origin	https://github.com/hashcat/hashcat.git (push)
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	src/TAGS

nothing added to commit but untracked files present (use "git add" to track)
```
