### ISSUE TITLE
Specifying POCL_DEBUG_LLVM_PASSES causes segfault

### ISSUE THREAD

**Issue by jmather-sesi** [pocl/pocl#1282]
I'm looking into a performance issue and I found that specifying POCL_DEBUG_LLVM_PASSES causes applications to segfault. The stacktrace is:

```
Thread 1 "mixbench-ocl" received signal SIGSEGV, Segmentation fault.
0x0000fffff7d7ed60 in InitializeLLVM () at ~/pocl-4.0/lib/CL/pocl_llvm_utils.cc:363
363	      O->addOccurrence(1, StringRef("debug"), StringRef("true"), false);
(gdb) bt
#0  0x0000fffff7d7ed60 in InitializeLLVM () at ~/pocl-4.0/lib/CL/pocl_llvm_utils.cc:363
#1  0x0000fffff7cfbe0c in POclCreateContext (properties=0xffffffffec58, num_devices=1, devices=0xffffffffeb88, pfn_notify=0x0, user_data=0x0, 
    errcode_ret=0xffffffffeb94) at ~/pocl-4.0/lib/CL/clCreateContext.c:146
#2  0x0000aaaaaaaa5094 in mixbenchGPU ()
#3  0x0000aaaaaaaa1c20 in main ()
```

POCL was compiled from the 4.0 release with LLVM 16 on aarch64.

Is it possible that LLVM changed the flag name?

**Comment by jmather-sesi** [comment]
According to [this](https://stackoverflow.com/a/52674901), it's probably due to the fact that I'm using a build of LLVM and clang from the Ubuntu package manager, which most likely was compiled without support for this flag.

Leaving this here in case others run into this.
