### ISSUE TITLE
Occasional LLVM crashes with slightly odd types

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#1440]
While working on PyOpenCL tests, the kernel in this reproducer was generated:
```py
import numpy as np
import pyopencl as cl
import pyopencl.array as cl_ary

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

prg = cl.Program(ctx, """

        __kernel void axpb(__global uchar *z__base, long z__offset, double a, __global uchar *x__base, long x__offset, uchar b, long n)
        {
          int lid = get_local_id(0);
          int gsize = get_global_size(0);
          int work_group_start = get_local_size(0)*get_group_id(0);
          long i;

          __global uchar *z = (__global uchar *) ((__global char *) z__base + z__offset);
__global uchar *x = (__global uchar *) ((__global char *) x__base + x__offset);;
          for (i = work_group_start + lid; i < n; i += gsize)
          {
            z[i] = a*x[i] + b;
          }
          
          ;
        }
        """).build()

z = cl_ary.zeros(queue, 10, dtype=np.uint8)
x = cl_ary.zeros(queue, 10, dtype=np.uint8)
prg.axpb(queue, (128,), (128,), z.data, np.int64(0), np.double(5), x.data, np.int64(0), np.uint8(3), np.int64(10))
```

About once every ten runs, this crashes for me with the following traceback (or similar):
```
#0  0x00007fc81762311d in llvm::EVT::isExtendedVector() const () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#1  0x00007fc8175f402a in llvm::TargetLoweringBase::getTypeConversion(llvm::LLVMContext&, llvm::EVT) const () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#2  0x00007fc81778cd6b in ?? () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#3  0x00007fc81779090a in llvm::SelectionDAG::LegalizeTypes() () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#4  0x00007fc81788c08f in llvm::SelectionDAGISel::CodeGenAndEmitDAG() () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#5  0x00007fc81788b5d2 in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#6  0x00007fc81788977e in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#7  0x00007fc819da4003 in ?? () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#8  0x00007fc8173e3ee4 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#9  0x00007fc81715c58f in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#10 0x00007fc817162003 in llvm::FPPassManager::runOnModule(llvm::Module&) () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#11 0x00007fc81715cc84 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /lib/x86_64-linux-gnu/libLLVM.so.18.1
#12 0x00007fc83b3ab15b in pocl_llvm_codegen () from /opt/pocl-main/lib/libpocl.so
#13 0x00007fc83b34333c in llvm_codegen () from /opt/pocl-main/lib/libpocl.so
#14 0x00007fc83b3457fe in pocl_check_kernel_disk_cache () from /opt/pocl-main/lib/libpocl.so
#15 0x00007fc83b345e95 in pocl_check_kernel_dlhandle_cache () from /opt/pocl-main/lib/libpocl.so
#16 0x00007fc83debd315 in pocl_pthread_driver_thread () from /opt/pocl-main/lib/pocl/libpocl-devices-pthread.so
#17 0x00007fc841aa145c in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#18 0x00007fc841b21bbc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
Reproducible with:
- pocl 7f568a490da1301608d6d82bae5dbe021fd1ffef (`main` as of this moment) and Debian's LLVM 1:18.1.2-1
- pocl 0bffce03b71c2be14ced90019418e943fd770114 (`release_5_0`) and Debian's LLVM 17.0.6-9.

I'm on a Raptor Lake mobile CPU, which LLVM 17 detected as `goldmont`, but LLVM 18 detects more appropriately as `alderlake`.

**Comment by pjaaskel** [comment]
This could be an LLVM issue. Please retry and reopen if you can still reproduce this with the latest main revision and/or the latest LLVM.

**Comment by inducer** [comment]
Doesn't seem to reproduce with 9cf3654.
