### ISSUE TITLE
Segfault of cross-compiled pocl with statically linked LLVM.

### ISSUE THREAD

**Issue by ilyaikik** [pocl/pocl#1451]
Hello!
Please help me with the next issue.

I'm building pocl with yocto for target arm cortex-a9 machine. And I have a recipe for that.

cmake parameters are next:
```
EXTRA_OECMAKE = "-DSTATIC_LLVM=ON \
                                   -DCMAKE_SYSTEM_NAME=Linux \
                                   -DCMAKE_BUILD_TYPE=Release \
                                   -DCL_DISABLE_HALF=1 \
                                   -DPATCH_EXEC=patch \
                                   -DXARGS_EXEC=/usr/bin/xargs \
                                   -DENABLE_ICD=OFF \
                                   -DDEFAULT_ENABLE_ICD=OFF \
                                   -DLLC_TRIPLE=arm-linux-gnueabihf \
                                   -DLLVM_HOST_TARGET=arm-linux-gnueabihf \
                                   -DLLC_HOST_CPU=cortex-a9 \
"
```
I've completely disabled icd as I want libOpenCL from pocl to be the single possible implementation on the target machine.

The problem is (I've tried pocl 5.0 and 3.0), that I have a segfault somewhere in llvm statically linked to libOpenCL. Here is gdb backtrace of the program running on ARM target and trying to compuile some `.cl` kernels:
```
#0  0x70f62f3c in __closedir (dirp=0x2) at ../sysdeps/unix/sysv/linux/closedir.c:44
#1  0x73f6f81c in llvm::sys::fs::detail::directory_iterator_destruct(llvm::sys::fs::detail::DirIterState&) () from /usr/lib/libOpenCL.so.2
#2  0x7197b82c in llvm::sys::fs::detail::DirIterState::~DirIterState (this=<optimized out>, this=<optimized out>) at /usr/include/llvm/Support/FileSystem.h:1411
#3  __gnu_cxx::new_allocator<llvm::sys::fs::detail::DirIterState>::destroy<llvm::sys::fs::detail::DirIterState> (__p=0x65d8b1dc, this=0x65d8b1dc) at /usr/include/c++/11.4.0/ext/new_allocator.h:168
#4  std::allocator_traits<std::allocator<llvm::sys::fs::detail::DirIterState> >::destroy<llvm::sys::fs::detail::DirIterState> (__p=0x65d8b1dc, __a=...) at /usr/include/c++/11.4.0/bits/alloc_traits.h:535
#5  std::_Sp_counted_ptr_inplace<llvm::sys::fs::detail::DirIterState, std::allocator<llvm::sys::fs::detail::DirIterState>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x65d8b1d0) at /usr/include/c++/11.4.0/bits/shared_ptr_base.h:528
#6  0x73f4d4b4 in (anonymous namespace)::RealFSDirIter::~RealFSDirIter() () from /usr/lib/libOpenCL.so.2
#7  0x71d2cf82 in clang::driver::RocmInstallationDetector::getInstallationPathCandidates() () from /usr/lib/libOpenCL.so.2
#8  0x71d2e458 in clang::driver::RocmInstallationDetector::detectHIPRuntime() () from /usr/lib/libOpenCL.so.2
#9  0x71d2e2ac in clang::driver::RocmInstallationDetector::RocmInstallationDetector(clang::driver::Driver const&, llvm::Triple const&, llvm::opt::ArgList const&, bool, bool) () from /usr/lib/libOpenCL.so.2
#10 0x71d8f990 in clang::driver::toolchains::Generic_GCC::Generic_GCC(clang::driver::Driver const&, llvm::Triple const&, llvm::opt::ArgList const&) () from /usr/lib/libOpenCL.so.2
#11 0x71d9c9a8 in clang::driver::toolchains::Linux::Linux(clang::driver::Driver const&, llvm::Triple const&, llvm::opt::ArgList const&) () from /usr/lib/libOpenCL.so.2
#12 0x71d12cf0 in std::_MakeUniq<clang::driver::toolchains::Linux>::__single_object std::make_unique<clang::driver::toolchains::Linux, clang::driver::Driver const&, llvm::Triple const&, llvm::opt::ArgList const&>(clang::driver::Driver const&, llvm::Triple const&, llvm::opt::ArgList const&) () from /usr/lib/libOpenCL.so.2
#13 0x71d027b0 in clang::driver::Driver::getToolChain(llvm::opt::ArgList const&, llvm::Triple const&) const () from /usr/lib/libOpenCL.so.2
#14 0x71d05210 in clang::driver::Driver::BuildCompilation(llvm::ArrayRef<char const*>) () from /usr/lib/libOpenCL.so.2
#15 0x7196f320 in pocl_invoke_clang (Device=Device@entry=0x5e54f0, Args=Args@entry=0x67ef95dc) at .../pocl/lib/CL/pocl_llvm_build.cc:1042
#16 0x7193f496 in llvm_codegen (output=output@entry=0x65d01388 "./ComputeKernels/Temp/LG/DGFCCANLELMDKNOAHBDKLOLJOLHCJHEPPNLGF/convertUYVYtoY/64-1-1-goffs0-smallgrid/convertUYVYtoY.so", device_i=device_i@entry=0, kernel=kernel@entry=0x6ab17460, device=0x5e54f0, 
    command=command@entry=0x4ea7d920, specialize=specialize@entry=1) at .../pocl/lib/CL/devices/common.c:225
#17 0x71940fe2 in pocl_check_kernel_disk_cache (command=command@entry=0x4ea7d920, specialized=specialized@entry=1) at .../pocl/lib/CL/devices/common.c:983
#18 0x719413d0 in pocl_check_kernel_dlhandle_cache (command=command@entry=0x4ea7d920, retain=retain@entry=1, specialize=specialize@entry=1) at .../pocl/lib/CL/devices/common.c:1108
#19 0x6f0e1e38 in pocl_pthread_prepare_kernel (cmd=0x4ea7d920, data=0x0) at .../pocl/lib/CL/devices/pthread/pthread_scheduler.c:404
#20 pthread_scheduler_get_work (td=<optimized out>) at .../pocl/lib/CL/devices/pthread/pthread_scheduler.c:526
#21 pocl_pthread_driver_thread (p=<optimized out>) at .../pocl/lib/CL/devices/pthread/pthread_scheduler.c:589
#22 0x70f3cf2e in start_thread (arg=0x585c6e69) at pthread_create.c:442
#23 0x70f8d740 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:74 from /lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

As we see in #0 __closedir receive `dirp=0x2` memory pointer that could not be correct and segfault happens.

But

If I build pocl with `-DSTATIC_LLVM=OFF` it will try to link to shared clang-llvm libraries laying in the target ARM machine filesystem while running the application. And `.cl` kernels can be compiled successfully.

Please, help me to understand what is going on. Why statically linked llvm produce segfault and the shared one - not? They should be the same... Because I use the same yocto project environment to build pocl and to build image for the target ARM machine.

**Comment by ilyaikik** [comment]
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Hwloc_VERSION 1.11.13
-- llvm-config's LLVM_VERSION_FULL is: 14.0.3

**Comment by pjaaskel** [comment]
From the backtrace, it seems the crash happens while the RoCm toolchain tries to detect so files in the filesystem?

```
#6  0x73f4d4b4 in (anonymous namespace)::RealFSDirIter::~RealFSDirIter() () from /usr/lib/libOpenCL.so.2
#7  0x71d2cf82 in clang::driver::RocmInstallationDetector::getInstallationPathCandidates() () from /usr/lib/libOpenCL.so.2
#8  0x71d2e458 in clang::driver::RocmInstallationDetector::detectHIPRuntime() () from /usr/lib/libOpenCL.so.2
#9  0x71d2e2ac in clang::driver::RocmInstallationDetector::RocmInstallationDetector(clang::driver::Driver const&, llvm::Triple const&, llvm::opt::ArgList const&, bool, bool) () from /usr/lib/libOpenCL.so.2
#10 0x71d8f990 in clang::driver::toolchains::Generic_GCC::Generic_GCC(clang::driver::Driver const&, llvm::Triple const&, llvm::opt::ArgList const&) () from /usr/lib/libOpenCL.so.2
#11 0x71d9c9a8 in clang::driver::toolchains::Linux::Linux(clang::driver::Driver const&, llvm::Triple const&, llvm::opt::ArgList const&) () from /usr/lib/libOpenCL.so.2
```
Perhaps try disabling the AMD/HSA-toolchain in the LLVM build?

In general, there are some notes on cross-compilation in [ToolchainExample.cmake](https://github.com/pocl/pocl/blob/main/ToolchainExample.cmake). Did you notice that one?

**Comment by franz** [comment]
This is somewhat similar to a bug with Blender & Luxmark from a long time ago.

Where is the statically linked LLVM from ? was it actually built on the target system, or cross-compiled for the target system ? or is it just downloaded prebuilt binaries that LLVM project supplies (at https://releases.llvm.org/), or copied binaries from other system ? If it is the second case, then that is likely the problem. This has caused similar crashes with Blender & Luxmark, because Clang/LLVM link against C++ libraries (like libstdc++) and those are not ABI compatible between different systems & versions. You need to build or cross-compile LLVM (and all parts of your application) for the **exact** OS & libraries you're going to run on.
