### ISSUE TITLE
pocl crashes when multiple processes access the kernel cache

### ISSUE THREAD

**Issue by matthiasdiener** [pocl/pocl#1480]
The following simple code crashes when building kernels in a multi-process application:

```python
# Note that this code doesn't actually use MPI
import pyopencl as cl

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

for i in range(1000):
    # Build 1000 different kernels
    print(i)
    prg = cl.Program(ctx, "__kernel void f() {int x = " + str(i) + ";}").build()

print("done")
```

```console
$ export PYOPENCL_NO_CACHE=1  # make sure pyopencl itself does not cache
$ mpirun -n 8 python t.py
Traceback (most recent call last):
  File "/Users/mdiener/Work/emirge/pyopencl/t.py", line 22, in <module>
    """ + "c[gid] = a[gid] + b[gid];" * i + "}").build()
                                                 ^^^^^^^
  File "/Users/mdiener/Work/emirge/pyopencl/pyopencl/__init__.py", line 510, in build
    self._build_and_catch_errors(
  File "/Users/mdiener/Work/emirge/pyopencl/pyopencl/__init__.py", line 566, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'cpu' on 'Portable Computing Language' at 0x14d10fe00>:

Device cpu failed to build the program

$ export POCL_KERNEL_CACHE=0  # the same code runs fine with the cache deactivated
$ mpirun -n 8 python t.py
done
$ 
```

It usually fails with less than 100 kernels built. There may be an issue with the cache locking.

cc: @inducer , https://github.com/inducer/pyopencl/pull/749

related: #430, #434, #466

**Comment by pjaaskel** [comment]
Are the MPI ranks on different nodes and are you using NFS for the kcache?

**Comment by pjaaskel** [comment]
We rely on atomicity of 'mv'. We used to have a lock file but it was brittle to crashing applications leaving them hanging.

**Comment by franz** [comment]
I've found the bug, there was an unnecessary `pocl_remove` call which was causing the problem. Will be fixed in main branch soon.

**Comment by matthiasdiener** [comment]
In my tests, [ed97458](https://github.com/pocl/pocl/commit/ed97458ba737be9057f322594b7ff5701ad79b1f) appears to have fixed the issue. Thank you @franz!
