### ISSUE TITLE
CUDA: Cannot find symbol _Z39atomic_compare...  in kernel library

### ISSUE THREAD

**Issue by linehill** [pocl/pocl#1482]
The attached [SPIR-V](https://github.com/pocl/pocl/files/15417263/missing-atomic-sym-reduced.tar.gz), derived from a HeCBench case, features an OpAtomicCompareExchange instruction that seems to cause the following error:
```
[<pyopencl.Device 'NVIDIA GeForce RTX 3060' on 'Portable Computing Language' at 0x5f0938ccb560>]
Traceback (most recent call last):
  File "/home/linehill/dev/ws-mesa/sandbox/pocl-cuda-compilation/./build-only.py", line 8, in <module>
    prog = cl.Program(ctx, spirv).build(options=["-cl-std=CL3.0"])
  File "/home/linehill/.local/lib/python3.10/site-packages/pyopencl/__init__.py", line 508, in build
    self._build_and_catch_errors(
  File "/home/linehill/.local/lib/python3.10/site-packages/pyopencl/__init__.py", line 564, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'NVIDIA GeForce RTX 3060' on 'Portable Computing Language' at 0x5f0938ccb560>:

Error(s) while linking: 
Cannot find symbol _Z39atomic_compare_exchange_strong_explicitPVU7_AtomiciPii12memory_orderS3_12memory_scope in kernel library
Device NVIDIA GeForce RTX 3060 failed to build the program

(options: -cl-std=CL3.0 -I /home/linehill/.local/lib/python3.10/site-packages/pyopencl/cl)
```
Note: I'm using [patched llvm-spirv](https://github.com/franz/SPIRV-LLVM-Translator/tree/llvm-17-target-as) that maps storage classes to NVPTX address spaces.

**Comment by franz** [comment]
This seems like a problem with the SPIRV wrapper (the mangled name does not have the PoCL's library prefix).
