### ISSUE TITLE
Level0 aborts when calling clMemFreeINTEL with multi-device context

### ISSUE THREAD

**Issue by linehill** [pocl/pocl#1548]
PoCL aborts in the Level0 device when calling `clMemFreeINTEL` with CPU+Level0 context and a device allocation (`Dev0Mem` in the reproducer) targeting the CPU device.

Reproducer:
```c++
#define CL_HPP_ENABLE_EXCEPTIONS
#include "CL/opencl.hpp"

#include <cstdlib>
#include <iostream>
#include <string>

#define ASSERT_SUCCESS(_exp)                                                   \
  do {                                                                         \
    if ((_exp) != CL_SUCCESS) {                                                \
      std::cerr << "OpenCL error at " << __FILE__ << ":" << __LINE__ << "\n";  \
      exit(2);                                                                 \
    }                                                                          \
  } while (0)

template <typename FnTy>
FnTy LoadOclExtFn(cl::Platform &P, const std::string &FnName) {
  auto PId = P.Wrapper<cl_platform_id>::get();
  auto TheFn = reinterpret_cast<FnTy>(
      clGetExtensionFunctionAddressForPlatform(PId, FnName.c_str()));
  if (!TheFn)
    throw std::runtime_error(std::string("Could not load '") + FnName + "'");
  return TheFn;
}

int main() try {
  unsigned PlatformIdx = 0;

  std::vector<cl::Platform> Platforms;
  cl::Platform::get(&Platforms);
  cl::Platform Platform = Platforms.at(PlatformIdx);
  std::cout << "Selected platform: " << Platform.getInfo<CL_PLATFORM_NAME>()
            << std::endl;

  std::vector<cl::Device> Devices;
  Platform.getDevices(CL_DEVICE_TYPE_ALL, &Devices);
  unsigned DevIdx = 0;
  for (auto &Dev : Devices)
    std::cout << "Devices[" << DevIdx++
              << "]: " << Dev.getInfo<CL_DEVICE_NAME>() << std::endl;
  if (Devices.size() < 2)
    return 2;

  auto AllocDevMem =
      LoadOclExtFn<clDeviceMemAllocINTEL_fn>(Platform, "clDeviceMemAllocINTEL");
  auto FreeMem = LoadOclExtFn<clMemFreeINTEL_fn>(Platform, "clMemFreeINTEL");

  auto Ctx = cl::Context(Devices);

  cl_int Err;
  void *Dev0Mem = AllocDevMem(Ctx.get(), Devices[0].get(), nullptr, 8, 8, &Err);
  ASSERT_SUCCESS(Err);
  Err = FreeMem(Ctx.get(), Dev0Mem);
  ASSERT_SUCCESS(Err);

  void *Dev1Mem = AllocDevMem(Ctx.get(), Devices[1].get(), nullptr, 8, 8, &Err);
  ASSERT_SUCCESS(Err);
  Err = FreeMem(Ctx.get(), Dev1Mem);
  ASSERT_SUCCESS(Err);

  return 0;
} catch (cl::Error &Ex) {
  std::cerr << "Caught OpenCL exception: " << Ex.what() << "\n";
  std::cerr << "Error code: " << Ex.err() << "\n";
  return 2;
} catch (std::exception &Ex) {
  std::cerr << "Caught STL exception: " << Ex.what() << "\n";
  return 2;
}
```
Output:
```
Selected platform: Portable Computing Language
Devices[0]: cpu-skylake-Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Devices[1]: Intel(R) HD Graphics 530
Error 78000004 from LevelZero API:
Res
../launch-pocl-build-all: line 12: 236718 Aborted                 (core dumped) "$@"
```

Backtrace:
```
Thread 1 "mdev-ctx" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737352615744) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737352615744)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737352615744) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737352615744, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007ffff7842476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff78287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7789b3e in pocl_level0_abort_on_ze_error (permit_quiet_exit=0, 
    status=ZE_RESULT_ERROR_INVALID_ARGUMENT, line=3062, func=0x7ffff77beed7 "freeMem", 
    code=0x7ffff77bbaf7 "Res")
    at /mnt/md1/linehill/pocl-space/pocl/lib/CL/devices/level0/level0-driver.cc:89
#6  0x00007ffff77985af in pocl::Level0Device::freeMem (this=0x5555569b5380, Ptr=0x555556f19c80)
    at /mnt/md1/linehill/pocl-space/pocl/lib/CL/devices/level0/level0-driver.cc:3062
#7  0x00007ffff77600df in pocl_level0_usm_free (Dev=0x5555569b3f80, SvmPtr=0x555556f19c80)
    at /mnt/md1/linehill/pocl-space/pocl/lib/CL/devices/level0/pocl-level0.cc:1523
#8  0x00007ffff74b0eb7 in pocl_mem_free_intel (context=0x555556f155d0, 
    usm_pointer=0x555556f19c80, blocking=0)
    at /mnt/md1/linehill/pocl-space/pocl/lib/CL/clMemFreeINTEL.c:109
#9  0x00007ffff74b10ff in POclMemFreeINTEL (context=0x555556f155d0, usm_pointer=0x555556f19c80)
    at /mnt/md1/linehill/pocl-space/pocl/lib/CL/clMemFreeINTEL.c:154
#10 0x0000555555557db4 in main () at mdev-ctx.cpp:53
```

**Comment by franz** [comment]
should be fixed in main
