### ISSUE TITLE
Segmentation fault in pocl_llvm_generate_workgroup_function

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#199]
This program

https://gist.github.com/inducer/4a186225fc26700de99b

crashes with

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffdcea0a12 in llvm::Value::getValueID (this=0x0) at /usr/lib/llvm-3.6/include/llvm/IR/Value.h:382
382         return SubclassID;
(gdb) bt
#0  0x00007fffdcea0a12 in llvm::Value::getValueID (this=0x0) at /usr/lib/llvm-3.6/include/llvm/IR/Value.h:382
#1  0x00007fffdceb1eb4 in llvm::Instruction::getOpcode (this=0x0) at /usr/lib/llvm-3.6/include/llvm/IR/Instruction.h:87
#2  0x00007fffdced04ed in llvm::PHINode::classof (I=0x0) at /usr/lib/llvm-3.6/include/llvm/IR/Instructions.h:2263
#3  0x00007fffdced2388 in llvm::isa_impl<llvm::PHINode, llvm::Instruction, void>::doit (Val=...) at /usr/lib/llvm-3.6/include/llvm/Support/Casting.h:56
#4  0x00007fffdced8811 in llvm::isa_impl_cl<llvm::PHINode, llvm::Instruction const*>::doit (Val=0x0) at /usr/lib/llvm-3.6/include/llvm/Support/Casting.h:96
#5  0x00007fffdced8768 in llvm::isa_impl_wrap<llvm::PHINode, llvm::Instruction const*, llvm::Instruction const*>::doit (Val=@0x7fffffffc178: 0x0) at /usr/lib/llvm-3.6/include/llvm/Support/Casting.h:122
#6  0x00007fffdced85b2 in llvm::isa_impl_wrap<llvm::PHINode, llvm::Instruction* const, llvm::Instruction const*>::doit (Val=@0x7fffffffc1b8: 0x0) at /usr/lib/llvm-3.6/include/llvm/Support/Casting.h:114
#7  0x00007fffdced827f in llvm::isa<llvm::PHINode, llvm::Instruction*> (Val=@0x7fffffffc1b8: 0x0) at /usr/lib/llvm-3.6/include/llvm/Support/Casting.h:134
#8  0x00007fffdced7f32 in llvm::dyn_cast<llvm::PHINode, llvm::Instruction> (Val=0x0) at /usr/lib/llvm-3.6/include/llvm/Support/Casting.h:298
#9  0x00007fffdcee4eb4 in BreakConstantGEPs::runOnFunction (this=0x1385590, F=...) at BreakConstantGEPs.cpp:308
#10 0x00007fffdad5f3a7 in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
#11 0x00007fffdad5f42b in llvm::FPPassManager::runOnModule(llvm::Module&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
#12 0x00007fffdad61e19 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
#13 0x00007fffdcea75b7 in pocl_llvm_generate_workgroup_function (device=0x12d9970, kernel=0x1016480, local_x=16, local_y=1, local_z=1) at pocl_llvm_api.cc:1356
#14 0x00007fffdce85db3 in POclEnqueueNDRangeKernel (command_queue=0x12da2e0, kernel=0x1016480, work_dim=1, global_work_offset=0x0, global_work_size=0x7fffffffd500, local_work_size=0x7fffffffd4e0, num_events_in_wait_list=0, event_wait_list=0x0, event=0x7fffffffd338) at clEnqueueNDRangeKernel.c:240
#15 0x00007fffea2aefbe in _call_func<int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**), 0, 1, 2, 3, 4, 5, 6, 7, 8, _cl_command_queue* const&, _cl_kernel* const&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, unsigned long, _cl_event**, _cl_event**> (args=..., func=<optimized out>) at src/c_wrapper/function.h:38
#16 call_tuple<int (*&)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**), std::tuple<_cl_command_queue* const&, _cl_kernel* const&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, unsigned long, _cl_event**, _cl_event**> > (args=<optimized out>, func=<synthetic pointer>) at src/c_wrapper/function.h:49
#17 call<__CLArgGetter, int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**)> (func=<optimized out>, this=0x7fffffffd360) at src/c_wrapper/function.h:108
#18 clcall<int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**)> (name=0x7fffea2b7c3e "clEnqueueNDRangeKernel", func=<optimized out>, this=0x7fffffffd360) at src/c_wrapper/error.h:186
#19 call_guarded<command_queue*&, kernel*&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, pyopencl_buf<_cl_event*> const&, _CLObjOutArg<event>, _cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**> (
    name=0x7fffea2b7c3e "clEnqueueNDRangeKernel", func=<optimized out>) at src/c_wrapper/error.h:218
#20 <lambda()>::operator()(void) const (__closure=__closure@entry=0x7fffffffd440) at src/c_wrapper/kernel.cpp:180
#21 0x00007fffea2af457 in retry_mem_error<enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()> > (func=...) at src/c_wrapper/error.h:294
#22 operator() (__closure=<synthetic pointer>) at src/c_wrapper/error.h:307
#23 c_handle_error<c_handle_retry_mem_error(Func&&) [with Func = enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()>]::<lambda()> > (func=...) at src/c_wrapper/error.h:271
#24 c_handle_retry_mem_error<enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()> > (func=<optimized out>) at src/c_wrapper/error.h:307
#25 enqueue_nd_range_kernel (evt=0x7fffe97fba70, _queue=<optimized out>, _knl=<optimized out>, work_dim=1, global_work_offset=0x0, global_work_size=0x7fffffffd500, local_work_size=0x7fffffffd4e0, _wait_for=0x0, num_wait_for=0) at src/c_wrapper/kernel.cpp:181
#26 0x00007fffea259e73 in _cffi_f_enqueue_nd_range_kernel (self=<optimized out>, args=<optimized out>) at build/temp.linux-x86_64-2.7/pyopencl._cffi.cpp:4525
#27 0x00000000004c9ae5 in PyEval_EvalFrameEx ()
#28 0x00000000004c8329 in PyEval_EvalCodeEx ()
#29 0x00000000004c9ff6 in PyEval_EvalFrameEx ()
#30 0x00000000004e42d0 in ?? ()
#31 0x0000000000502608 in ?? ()
#32 0x000000000056ef6b in ?? ()
#33 0x00000000004ca803 in PyEval_EvalFrameEx ()
#34 0x00000000004ca272 in PyEval_EvalFrameEx ()
#35 0x00000000004c8329 in PyEval_EvalCodeEx ()
#36 0x000000000050111f in ?? ()
#37 0x00000000004f6e22 in PyRun_FileExFlags ()
#38 0x00000000004f5f17 in PyRun_SimpleFileExFlags ()
#39 0x0000000000497afd in Py_Main ()
#40 0x00007ffff6f14b45 in __libc_start_main (main=0x497590 <main>, argc=2, argv=0x7fffffffe2a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe298) at libc-start.c:287
#41 0x00000000004974b8 in _start ()
```

This, along with #197, accounts for the remaining serious issues in PyOpenCL's tests.

**Comment by inducer** [comment]
Confirmed fixed, thank you!
