### ISSUE TITLE
"Type not in ValueEnumerator" with LLVM 3.7

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#242]
POCL 522717b, LLVM r245534, Clang r245456.

Reproducer: https://gist.github.com/inducer/61364b4b188c348e3272

```
python: /home/andreas/pack/llvm/lib/Bitcode/Writer/ValueEnumerator.h:131: unsigned int llvm::ValueEnumerator::getTypeID(llvm::Type*) const: Assertion `I != TypeMap.end() && "Type not in ValueEnumerator!"' failed.
```

Backtrace

```
#0  0x00007ffff6f28107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6f294e8 in __GI_abort () at abort.c:89
#2  0x00007ffff6f21226 in __assert_fail_base (fmt=0x7ffff7057d08 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7fffdfc68830 "I != TypeMap.end() && \"Type not in ValueEnumerator!\"", 
    file=file@entry=0x7fffdfc687c0 "/home/andreas/pack/llvm/lib/Bitcode/Writer/ValueEnumerator.h", line=line@entry=131, 
    function=function@entry=0x7fffdfc6c1a0 <llvm::ValueEnumerator::getTypeID(llvm::Type*) const::__PRETTY_FUNCTION__> "unsigned int llvm::ValueEnumerator::getTypeID(llvm::Type*) const") at assert.c:92
#3  0x00007ffff6f212d2 in __GI___assert_fail (assertion=0x7fffdfc68830 "I != TypeMap.end() && \"Type not in ValueEnumerator!\"", 
    file=0x7fffdfc687c0 "/home/andreas/pack/llvm/lib/Bitcode/Writer/ValueEnumerator.h", line=131, 
    function=0x7fffdfc6c1a0 <llvm::ValueEnumerator::getTypeID(llvm::Type*) const::__PRETTY_FUNCTION__> "unsigned int llvm::ValueEnumerator::getTypeID(llvm::Type*) const")
    at assert.c:101
#4  0x00007fffdfc375b6 in llvm::ValueEnumerator::getTypeID (this=0x7fffffffb070, T=0x4d889a0) at /home/andreas/pack/llvm/lib/Bitcode/Writer/ValueEnumerator.h:131
#5  0x00007fffdfc331ab in WriteInstruction (I=..., InstID=135, VE=..., Stream=..., Vals=...) at /home/andreas/pack/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:1979
#6  0x00007fffdfc33b99 in WriteFunction (F=..., VE=..., Stream=...) at /home/andreas/pack/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:2136
#7  0x00007fffdfc3510e in WriteModule (M=0x6d43760, Stream=..., ShouldPreserveUseListOrder=false) at /home/andreas/pack/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:2401
#8  0x00007fffdfc3547c in llvm::WriteBitcodeToFile (M=0x6d43760, Out=..., ShouldPreserveUseListOrder=false) at /home/andreas/pack/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp:2502
#9  0x00007fffe131989d in pocl_write_module (module=module@entry=0x6d43760, 
    path=path@entry=0x7fffffffb470 "/home/andreas/.cache/pocl/kcache/CB/LFEGBLOKOBOBILACMDFMDFNGAOAEOKBHDOMOP/generate/16-1-1/parallel.bc", dont_rewrite=dont_rewrite@entry=0)
    at LLVMFileUtils.cc:277
#10 0x00007fffe12e14d3 in pocl_cache_write_kernel_parallel_bc (bc=bc@entry=0x6d43760, program=program@entry=0x2e7faa0, device_i=device_i@entry=0, kernel=kernel@entry=0x4e32260, 
    local_x=local_x@entry=16, local_y=local_y@entry=1, local_z=1) at pocl_cache.c:278
#11 0x00007fffe12e99ef in pocl_llvm_generate_workgroup_function (device=<optimized out>, kernel=kernel@entry=0x4e32260, local_x=local_x@entry=16, local_y=local_y@entry=1, 
    local_z=local_z@entry=1) at pocl_llvm_api.cc:1381
#12 0x00007fffe12d2eab in POclEnqueueNDRangeKernel (command_queue=0x2ac0170, kernel=0x4e32260, work_dim=1, global_work_offset=<optimized out>, global_work_size=<optimized out>, 
    local_work_size=<optimized out>, num_events_in_wait_list=0, event_wait_list=0x0, event=0x7fffffffca18) at clEnqueueNDRangeKernel.c:240
#13 0x00007fffe97e6bf4 in _call_func<int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**), 0, 1, 2, 3, 4, 5, 6, 7, 8, _cl_command_queue* const&, _cl_kernel* const&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, unsigned long, _cl_event**, _cl_event**> (args=..., func=<optimized out>) at src/c_wrapper/function.h:38
#14 call_tuple<int (*&)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**), std::tuple<_cl_command_queue* const&, _cl_kernel* const&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, unsigned long, _cl_event**, _cl_event**> > (args=<optimized out>, func=<synthetic pointer>) at src/c_wrapper/function.h:49
#15 ArgPack<CLArg, command_queue*, kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, pyopencl_buf<_cl_event*> const, _CLObjOutArg<event> >::call<__CLArgGetter, int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**)> (func=<optimized out>, this=0x7fffffffca70) at src/c_wrapper/function.h:108
#16 CLArgPack<command_queue*, kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, pyopencl_buf<_cl_event*> const, _CLObjOutArg<event> >::clcall<int (*)(_cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**)> (
    name=0x7fffe97eb508 "clEnqueueNDRangeKernel", func=<optimized out>, this=0x7fffffffca70) at src/c_wrapper/error.h:186
#17 call_guarded<command_queue*&, kernel*&, unsigned int&, unsigned long const*&, unsigned long const*&, unsigned long const*&, pyopencl_buf<_cl_event*> const&, _CLObjOutArg<event>, _cl_command_queue*, _cl_kernel*, unsigned int, unsigned long const*, unsigned long const*, unsigned long const*, unsigned int, _cl_event* const*, _cl_event**> (
    name=0x7fffe97eb508 "clEnqueueNDRangeKernel", func=<optimized out>) at src/c_wrapper/error.h:218
#18 <lambda()>::operator() (__closure=<synthetic pointer>) at src/c_wrapper/kernel.cpp:180
#19 retry_mem_error<enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()> > (func=...)
    at src/c_wrapper/error.h:294
#20 <lambda()>::operator() (__closure=<synthetic pointer>) at src/c_wrapper/error.h:307
#21 c_handle_error<c_handle_retry_mem_error(Func&&) [with Func = enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()>]::<lambda()> > (func=...) at src/c_wrapper/error.h:271
#22 c_handle_retry_mem_error<enqueue_nd_range_kernel(clbase**, clobj_t, clobj_t, cl_uint, const size_t*, const size_t*, const size_t*, clbase* const*, uint32_t)::<lambda()> > (
    func=<optimized out>) at src/c_wrapper/error.h:307
#23 enqueue_nd_range_kernel (evt=0x7fffcadba8b0, _queue=<optimized out>, _knl=0x6d43c60, work_dim=work_dim@entry=1, global_work_offset=0x0, global_work_size=0x7fffffffcb90, 
    local_work_size=0x0, _wait_for=0x0, num_wait_for=0) at src/c_wrapper/kernel.cpp:181
#24 0x00007fffe979cfe2 in _cffi_f_enqueue_nd_range_kernel (self=<optimized out>, args=<optimized out>) at build/temp.linux-x86_64-2.7/pyopencl._cffi.cpp:4540
#25 0x00000000004c9ae5 in PyEval_EvalFrameEx ()
#26 0x00000000004c8329 in PyEval_EvalCodeEx ()
#27 0x00000000004c9ff6 in PyEval_EvalFrameEx ()
#28 0x00000000004e42d0 in ?? ()
#29 0x00000000004cd352 in PyEval_EvalFrameEx ()
#30 0x00000000004e42d0 in ?? ()
#31 0x0000000000502608 in ?? ()
#32 0x000000000056ef6b in ?? ()
#33 0x00000000004ca803 in PyEval_EvalFrameEx ()
#34 0x00000000004c8329 in PyEval_EvalCodeEx ()
#35 0x00000000004c9ff6 in PyEval_EvalFrameEx ()
#36 0x00000000004c8329 in PyEval_EvalCodeEx ()
#37 0x00000000004c9ff6 in PyEval_EvalFrameEx ()
#38 0x00000000004c8329 in PyEval_EvalCodeEx ()
#39 0x00000000004cb577 in PyEval_EvalFrameEx ()
#40 0x00000000004c8329 in PyEval_EvalCodeEx ()
#41 0x000000000053627a in PyRun_StringFlags ()
#42 0x00000000004cf567 in PyEval_EvalFrameEx ()
#43 0x00000000004c8329 in PyEval_EvalCodeEx ()
#44 0x000000000050111f in ?? ()
#45 0x00000000004f6e22 in PyRun_FileExFlags ()
#46 0x00000000004f5f17 in PyRun_SimpleFileExFlags ()
#47 0x0000000000497afd in Py_Main ()
#48 0x00007ffff6f14b45 in __libc_start_main (main=0x497590 <main>, argc=3, argv=0x7fffffffe268, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe258) at libc-start.c:287
#49 0x00000000004974b8 in _start ()
```

**Comment by pjaaskel** [comment]
Finally found some time for this. Please reopen if it sill breaks for you.

**Comment by inducer** [comment]
Thank you! It seems like pocl now passes all of PyOpenCL's tests with LLVM 3.7. (Yay!)
