### ISSUE TITLE
everything fails with --disable-icd 

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#261]
When built with --disable-icd, libhwloc initialization ends up initializing pocl's dynlib again ending up with:

```
./example1 
Two passes with the same argument (-barriers) attempted to be registered!
UNREACHABLE executed at /mnt/olddisk1/work/llvm-build-temp/llvm-3.7/include/llvm/IR/LegacyPassNameParser.h:74!
Aborted (core dumped)
```

The backtrace:

```
gdb) bt
#0  0x00007ffff5c29cc9 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5c2d0d8 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff3b184ac in llvm::llvm_unreachable_internal(char const*, char const*, unsigned int) () from /home/visit0r/local/lib/libLLVM-3.7.so
#3  0x00007ffff320f6e3 in llvm::PassNameParser::passRegistered(llvm::PassInfo const*) () from /home/visit0r/local/lib/libLLVM-3.7.so
#4  0x00007ffff3210ef8 in llvm::PassRegistry::registerPass(llvm::PassInfo const&, bool) () from /home/visit0r/local/lib/libLLVM-3.7.so
#5  0x00007fffefab2b49 in RegisterPass (is_analysis=false, CFGOnly=false, Name=0x7ffff06c57d5 "Barrier canonicalization pass", PassArg=0x7ffff06be9c0 "barriers", this=0x7ffff118d7a0 <_ZN12_GLOBAL__N_1L1XE>) at /home/visit0r/local/include/llvm/PassSupport.h:127
#6  __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at CanonicalizeBarriers.cc:56
#7  _GLOBAL__sub_I_CanonicalizeBarriers.cc(void) () at CanonicalizeBarriers.cc:247
#8  0x00007ffff7dea13a in ?? () from /lib64/ld-linux-x86-64.so.2
#9  0x00007ffff7dea223 in ?? () from /lib64/ld-linux-x86-64.so.2
#10 0x00007ffff7deec70 in ?? () from /lib64/ld-linux-x86-64.so.2
#11 0x00007ffff7de9ff4 in ?? () from /lib64/ld-linux-x86-64.so.2
#12 0x00007ffff7dee3bb in ?? () from /lib64/ld-linux-x86-64.so.2
#13 0x00007ffff1c1d02b in ?? () from /lib/x86_64-linux-gnu/libdl.so.2
#14 0x00007ffff7de9ff4 in ?? () from /lib64/ld-linux-x86-64.so.2
#15 0x00007ffff1c1d62d in ?? () from /lib/x86_64-linux-gnu/libdl.so.2
#16 0x00007ffff1c1d0c1 in dlopen () from /lib/x86_64-linux-gnu/libdl.so.2
#17 0x00007ffff57af592 in ?? () from /usr/lib/x86_64-linux-gnu/libltdl.so.7
#18 0x00007ffff57ac17a in ?? () from /usr/lib/x86_64-linux-gnu/libltdl.so.7
#19 0x00007ffff57adcc3 in ?? () from /usr/lib/x86_64-linux-gnu/libltdl.so.7
#20 0x00007ffff57ae677 in lt_dlopenadvise () from /usr/lib/x86_64-linux-gnu/libltdl.so.7
#21 0x00007ffff57ae733 in lt_dlopenext () from /usr/lib/x86_64-linux-gnu/libltdl.so.7
#22 0x00007ffff59c6267 in ?? () from /usr/lib/x86_64-linux-gnu/libhwloc.so.5
#23 0x00007ffff57acccb in ?? () from /usr/lib/x86_64-linux-gnu/libltdl.so.7
#24 0x00007ffff57ac768 in ?? () from /usr/lib/x86_64-linux-gnu/libltdl.so.7
#25 0x00007ffff57ad249 in lt_dlforeachfile () from /usr/lib/x86_64-linux-gnu/libltdl.so.7
#26 0x00007ffff59c6746 in ?? () from /usr/lib/x86_64-linux-gnu/libhwloc.so.5
#27 0x00007ffff59c6b78 in ?? () from /usr/lib/x86_64-linux-gnu/libhwloc.so.5
#28 0x00007ffff59bf622 in hwloc_topology_init () from /usr/lib/x86_64-linux-gnu/libhwloc.so.5
#29 0x00007ffff6717738 in pocl_topology_detect_device_info (device=0x618cd0) at pocl_topology.c:41
#30 0x00007ffff6715de1 in pocl_pthread_init (device=0x618cd0, parameters=<optimized out>) at pthread.c:252
#31 0x00007ffff6714588 in pocl_init_devices () at devices.c:268
#32 0x00007ffff66fdf34 in POclCreateContextFromType (properties=properties@entry=0x7fffffffd3e0, device_type=device_type@entry=4294967295, pfn_notify=pfn_notify@entry=0x0, user_data=user_data@entry=0x0, errcode_ret=errcode_ret@entry=0x0) at clCreateContextFromType.c:51
#33 0x00007ffff61d739f in poclu_create_any_context () at misc.c:47
#34 0x00000000004011ef in exec_dot_product_kernel (
    program_source=program_source@entry=0x616f70 "#define USE_VECTOR_DATATYPES\n\n__kernel void \ndot_product (__global const float4 *a,  \n\t     __global const float4 *b, __global float *c) \n{ \n  int gid = get_global_id(0); \n\n#ifndef USE_VECTOR_DATATYPE"..., 
    n=n@entry=128, srcA=srcA@entry=0x617350, srcB=srcB@entry=0x617b60, dst=dst@entry=0x616d30) at example1_exec.c:32
#35 0x0000000000400f4c in main () at example1.c:85
```

**Comment by pjaaskel** [comment]
Removing the OpenCL plugin (apt-get remove libhwloc-plugins) solves this too.

**Comment by pjaaskel** [comment]
059966e3f619b3313a has a fix.

**Comment by franz** [comment]
OK, ungly commit is in both master & release_0_12, now just needs to test
