### ISSUE TITLE
cannot combine with previous `type-name` declaration specifier

### ISSUE THREAD

**Issue by muayyad-alsadi** [pocl/pocl#407]
POCL does not seem to work

I have the following versions
```
pocl-0.13-7.fc25.x86_64
clinfo-2.1.16.01.12-1.0.git20160207.f951686.fc24.x86_64
beignet-1.2.1-1.fc25.x86_64
mesa-libOpenCL-13.0.2-2.fc25.x86_64
opencl-utils-1-2.svn16.fc24.x86_64
```

my cpu is `Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz` and `lspci` gives

```00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
02:00.0 VGA compatible controller: NVIDIA Corporation GK208M [GeForce GT 730M] (rev a1)
```

the sessions is

```
[root@localhost ~]# curl -sSLO https://raw.githubusercontent.com/pyopencl/pyopencl/master/examples/demo.py
[root@localhost ~]# python demo.py
Choose platform:
[0] <pyopencl.Platform 'Clover' at 0x7f383af94580>
[1] <pyopencl.Platform 'Portable Computing Language' at 0x7f383351f020>
Choice [0]:1
Set the environment variable PYOPENCL_CTX='1' to avoid being asked again.
8 errors generated.
Traceback (most recent call last):
  File "demo.py", line 25, in <module>
    """).build()
  File "/usr/lib64/python2.7/site-packages/pyopencl/__init__.py", line 379, in build
    options=options, source=self._source)
  File "/usr/lib64/python2.7/site-packages/pyopencl/__init__.py", line 414, in _build_and_catch_errors
    raise err
pyopencl.cffi_cl.RuntimeError: clbuildprogram failed: BUILD_PROGRAM_FAILURE - 

Build on <pyopencl.Device 'pthread-Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz' on 'Portable Computing Language' at 0x55b99bdad5e0>:

error: /usr/share/pocl/include/pocl_types.h:46:9 <Spelling=<built-in>:76:37>: cannot combine with previous 'type-name' declaration specifier
error: /usr/share/pocl/include/pocl_types.h:46:9 <Spelling=<built-in>:76:28>: 'type-name' cannot be signed or unsigned
error: /usr/share/pocl/include/pocl_types.h:47:9 <Spelling=<built-in>:68:31>: cannot combine with previous 'type-name' declaration specifier
error: /usr/share/pocl/include/_kernel.h:196:1 <Spelling=/usr/share/pocl/include/_kernel.h:196:27>: invalid application of 'sizeof' to an incomplete type 'size_t' (aka 'struct error_undefined_type_long')
error: /usr/share/pocl/include/_kernel.h:197:1 <Spelling=/usr/share/pocl/include/_kernel.h:197:30>: invalid application of 'sizeof' to an incomplete type 'ptrdiff_t' (aka 'struct error_undefined_type_long')
error: /usr/share/pocl/include/_kernel.h:198:1 <Spelling=/usr/share/pocl/include/_kernel.h:198:29>: invalid application of 'sizeof' to an incomplete type 'intptr_t' (aka 'struct error_undefined_type_long')
error: /usr/share/pocl/include/_kernel.h:199:1 <Spelling=/usr/share/pocl/include/_kernel.h:199:30>: invalid application of 'sizeof' to an incomplete type 'uintptr_t' (aka 'struct error_undefined_type_long')
error: /root/.cache/pocl/kcache/temp_28rqbQ.cl:5:13: calling 'get_global_id' with incomplete return type 'size_t' (aka 'struct error_undefined_type_long')

(options: -I /usr/lib64/python2.7/site-packages/pyopencl/cl)
(source saved as /tmp/tmpJa8PaI.cl)
```

**Comment by eschnett** [comment]
This error message means that pocl thinks that `size_t` etc. should be equivalent to `long`, i.e. that you are running on a 64-bit platform. At the same time, pocl doesn't have a definition of `long` available. This looks to me like a configuration problem when pocl was installed. Do you have more information about log files etc.?

**Comment by muayyad-alsadi** [comment]
I'm using fedora 25, and stock packages. The following example works

https://github.com/muayyad-alsadi/OpenCL-HelloWorld

and here its run log

https://paste.fedoraproject.org/508914/48207613/

but the [demo.py](https://raw.githubusercontent.com/pyopencl/pyopencl/master/examples/demo.py) does not work.  I'm using `python2-pyopencl-2015.2-4.fc25.x86_64` [build](https://koji.fedoraproject.org/koji/buildinfo?buildID=783063) you can find [build logs here](https://kojipkgs.fedoraproject.org//packages/python-pyopencl/2015.2/4.fc25/data/logs/x86_64/build.log)

if you need the build logs of any package you can refer to fedora apps like this link https://admin.fedoraproject.org/pkgdb/package/rpms/pocl/ and https://koji.fedoraproject.org/koji/buildinfo?buildID=798667

**Comment by muayyad-alsadi** [comment]
clinfo output gives such errors around line 300, which makes me suspect it's not related to pyopencl

[clinfo.txt](https://github.com/pocl/pocl/files/659523/clinfo.txt)

```
  Platform Name                                   Portable Computing Language
Number of devices                                 1
  Device Name                                     pthread-Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  Device Vendor                                   GenuineIntel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0 pocl
  Driver Version                                  0.13
  Device OpenCL C Version                         OpenCL C 2.0
  Device Type                                     CPU, Default
  Device Profile                                  FULL_PROFILE
  Max compute units                               8
  Max clock frequency                             3500MHz
  Device Partition                                (core)
    Max number of sub-devices                     8
    Supported partition types                     equally, by counts
  Max work item dimensions                        3
  Max work item sizes                             4096x4096x4096
  Max work group size                             4096
  Preferred work group size multiple              error: /usr/share/pocl/include/pocl_types.h:46:9 <Spelling=<built-in>:76:37>: cannot combine with previous 'type-name' declaration specifier
error: /usr/share/pocl/include/pocl_types.h:46:9 <Spelling=<built-in>:76:28>: 'type-name' cannot be signed or unsigned```

**Comment by pjaaskel** [comment]
Please try pocl master to see if the issue has been fixed in the latest revision.

**Comment by muayyad-alsadi** [comment]
I want to have any hint from someone with more knowledge than me

if it's a bug in POCL why [OpenCL-HelloWorld](https://github.com/muayyad-alsadi/OpenCL-HelloWorld) but clinfo and demo.py does not?

> Please try pocl master to see if the issue has been fixed in the latest revision.

this build is from two days ago.
https://koji.fedoraproject.org/koji/buildinfo?buildID=820288

I can use it. but I want to make sure it's POCL issue not somewhere else

**Comment by ignatenkobrain** [comment]
@muayyad-alsadi yes, try the one from rawhide (but you need to run on rawhide as well, because of different versions of LLVM)

**Comment by muayyad-alsadi** [comment]
on rawhide I got this using `pocl.x86_64 0.14-0.2.git3fef5b5.fc26` and `python3-pyopencl.x86_64 2016.1-4.fc26`

```[root@deebd07d2736 /]# python3 demo.py
Choose platform:
[0] <pyopencl.Platform 'Portable Computing Language' at 0x7f282fe242e0>
Choice [0]:0
Set the environment variable PYOPENCL_CTX='0' to avoid being asked again.
1 error generated.
Traceback (most recent call last):
  File "demo.py", line 25, in <module>
    """).build()
  File "/usr/lib64/python3.5/site-packages/pyopencl/__init__.py", line 474, in build
    options_bytes=options_bytes, source=self._source)
  File "/usr/lib64/python3.5/site-packages/pyopencl/__init__.py", line 509, in _build_and_catch_errors
    raise err
pyopencl.cffi_cl.RuntimeError: clbuildprogram failed: BUILD_PROGRAM_FAILURE - 

Build on <pyopencl.Device 'pthread-Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz' on 'Portable Computing Language' at 0x55fab4c6c760>:

error: /usr/share/pocl/include/pocl_types.h:4:4: "cl_khr_fp64 requires cl_khr_int64"

(options: -I /usr/lib64/python3.5/site-packages/pyopencl/cl)
(source saved as /tmp/tmpxd1w6bqj.cl)
[root@deebd07d2736 /]# ```

**Comment by kraiskil** [comment]
> error: /usr/share/pocl/include/pocl_types.h:4:4: "cl_khr_fp64 requires cl_khr_int64"
Quite a while back there was trouble with OpenCL-C 'long', because Clang didn't define OpenCL-C types separately, but used the C types natively. So sizeof(long) was 4, at least on ARM 32bit. So OCL-C long could optionally (and, I think, against the specs) be disabled. 
Looking at the build logs you posted earlier, it seems long is not disabled for the x86_64 build, though.

**Comment by muayyad-alsadi** [comment]
> Quite a while back there was trouble with OpenCL-C 'long', because Clang didn't define OpenCL-C types separately,

what to install? what to pass to fix this?

why the error is different between first released and rawhide git prerelease

**Comment by ignatenkobrain** [comment]
@muayyad-alsadi 1) packaging fixes 2) more recent version

**Comment by muayyad-alsadi** [comment]
what is not different that it's still not work?

any help to get it right? is there something to be fixed from packaging side? or is it code to be fixed?

**Comment by muayyad-alsadi** [comment]
on ubuntu 16.10 (on docker) it works with no warning, versions:
```
ocl-icd-libopencl1 amd64 2.2.9-1
clinfo amd64 2.1.16.01.12-1
libpocl1 amd64 0.13-7 
pocl-opencl-icd amd64 0.13-7
python-pyopencl amd64 2015.2.4-1
```

results

```root@d0780123cf9d:/# python demo.py
Choose platform:
[0] <pyopencl.Platform 'Portable Computing Language' at 0x7fa90e2d3ae0>
Choice [0]:0
Set the environment variable PYOPENCL_CTX='0' to avoid being asked again.
[ 0.07145606  0.08942412  0.37392846 ...,  0.24030809  0.45121008
  0.9958275 ] [ 0.57842302  0.8551141   0.66119075 ...,  0.26979133  0.20714134
  0.06385801] [ 0.6498791   0.94453824  1.03511918 ...,  0.51009941  0.65835142
  1.05968547]
[ 0.  0.  0. ...,  0.  0.  0.]
0.0
```

**Comment by muayyad-alsadi** [comment]
can we know if this is a pyopencl issue or pocl issue? note on fedora pyopencl works with intel's beignet

**Comment by kraiskil** [comment]
I wonder if it may not be a clang issue?
One thing to test is if sizeof(long) in C is 8 the clang in rawhide.

**Comment by muayyad-alsadi** [comment]
```
#include<stdio.h>
void main() {
printf("%d\n", sizeof(long));
}
```

and

```
$ clang -o delme delme.c && ./delme
# ...
8
```

**Comment by pjaaskel** [comment]
There has been a lot of pyopencl etc. fixes. Please retry with LLVM 5.0 and pocl master and reopen if it still breaks.
