### ISSUE TITLE
clEnqueueNDRangeKernel double free or corruption 

### ISSUE THREAD

**Issue by jpsollie** [pocl/pocl#511]
gdb backtrace:
#0  0x00007fd8c076adde in raise () from /lib64/libc.so.6
#1  0x00007fd8c076c0e9 in abort () from /lib64/libc.so.6
#2  0x00007fd8c07a87e0 in __libc_message () from /lib64/libc.so.6
#3  0x00007fd8c07ae915 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007fd8c07af0ee in _int_free () from /lib64/libc.so.6
#5  0x00007fd8b0344d9b in free_kernel_arg_array () from /usr/local/lib64/libpocl.so.1.7.0
#6  0x00007fd8b0343de9 in work_group_scheduler () from /usr/local/lib64/libpocl.so.1.7.0
#7  0x00007fd8b034366e in pthread_scheduler_get_work () from /usr/local/lib64/libpocl.so.1.7.0
#8  0x00007fd8b034448f in pocl_pthread_driver_thread () from /usr/local/lib64/libpocl.so.1.7.0
#9  0x00007fd8c0ad340c in start_thread () from /lib64/libpthread.so.0
#10 0x00007fd8c081debf in clone () from /lib64/libc.so.6
kernel:
__kernel void startSearch(__constant uchar* hash, __constant uchar* ss, const size_t ss_len, __constant char* ds, const size_t key_len, __global uint* output)
piece of code where enqueueNDRaangeKernel is launched:
clEnqueueWriteBuffer (dev->command_queue, dev->output, CL_TRUE, 0, 64, answer, 0, NULL, NULL);
clEnqueueNDRangeKernel (dev->command_queue, dev->kernel, 3, NULL, workborder, workitems, 0, NULL, NULL);
clEnqueueReadBuffer (dev->command_queue, dev->output, CL_TRUE, 0, 64, dev->host_output, 0, NULL, NULL);
it never reaches the ReadBuffer, it prints the following:
/lib64/libc.so.6(+0x707db)[0x7fd8c07a87db]
/lib64/libc.so.6(+0x76915)[0x7fd8c07ae915]
/lib64/libc.so.6(+0x770ee)[0x7fd8c07af0ee]
/usr/local/lib64/libpocl.so.1.7.0(+0x12ad9b)[0x7fd8b0344d9b]
/usr/local/lib64/libpocl.so.1.7.0(+0x129de9)[0x7fd8b0343de9]
/usr/local/lib64/libpocl.so.1.7.0(+0x12966e)[0x7fd8b034366e]
/usr/local/lib64/libpocl.so.1.7.0(+0x12a48f)[0x7fd8b034448f]
/lib64/libpthread.so.0(+0x740c)[0x7fd8c0ad340c]
/lib64/libc.so.6(clone+0x3f)[0x7fd8c081debf]
on amd bdver1 compiled with GCC-7.1.0

**Comment by jpsollie** [comment]
sorry, I saw my local memory wasn't aligned properly.  My mistake, close issue
