### ISSUE TITLE
LLVM stuck compiling FP64 version of cos() on AVX512 hardware

### ISSUE THREAD

**Issue by franz** [pocl/pocl#551]
Seems to be stuck in some codegen pass:

```
Thread 2 (Thread 0x7f49968a4700 (LWP 17004)):
#0  0x00007f4998a0914b in llvm::SelectionDAG::Legalize() () from /usr/lib/llvm-5.0/lib/libLLVM-5.0.so.1
#1  0x00007f4998b02448 in llvm::SelectionDAGISel::CodeGenAndEmitDAG() () from /usr/lib/llvm-5.0/lib/libLLVM-5.0.so.1
#2  0x00007f4998b0bafb in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) () from /usr/lib/llvm-5.0/lib/libLLVM-5.0.so.1
#3  0x00007f4998b0d75b in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) () from /usr/lib/llvm-5.0/lib/libLLVM-5.0.so.1
#4  0x00007f4999e70c64 in (anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) ()
   from /usr/lib/llvm-5.0/lib/libLLVM-5.0.so.1
#5  0x00007f49987e9831 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) () from /usr/lib/llvm-5.0/lib/libLLVM-5.0.so.1
#6  0x00007f499865b9f2 in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /usr/lib/llvm-5.0/lib/libLLVM-5.0.so.1
#7  0x00007f499865ba83 in llvm::FPPassManager::runOnModule(llvm::Module&) () from /usr/lib/llvm-5.0/lib/libLLVM-5.0.so.1
#8  0x00007f499865c387 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/lib/llvm-5.0/lib/libLLVM-5.0.so.1
#9  0x00007f499bd4cd9d in pocl_llvm_codegen () from /home/franz/b_500/lib/CL/libpocl.so.1.7.0
#10 0x00007f499bd4f79c in llvm_codegen () from /home/franz/b_500/lib/CL/libpocl.so.1.7.0
---Type <return> to continue, or q <return> to quit---
#11 0x00007f499bd53ac4 in pocl_check_dlhandle_cache () from /home/franz/b_500/lib/CL/libpocl.so.1.7.0
#12 0x00007f499bd559e2 in pocl_pthread_driver_thread () from /home/franz/b_500/lib/CL/libpocl.so.1.7.0
#13 0x00007f499d68b494 in start_thread (arg=0x7f49968a4700) at pthread_create.c:333
#14 0x00007f499d3cdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

```

The same code using FP32 vectors compiles fine.

**Comment by franz** [comment]
oops, double post.
