### ISSUE TITLE
conformance relational tests / shuffle_built_in & shuffle_built_in_dual_input fail with LLVM 6

### ISSUE THREAD

**Issue by franz** [pocl/pocl#625]
These test ``shuffle()`` and ``shuffle2()``. The failure is in "X86InterleavedAccessGroup" which seems to be some x86-specific optimization pass. Interestingly pocl's internal shuffle / shuffle2 tests do not trigger it, and of the CTS only certain vector combinations trigger it.

short backtrace:

```
#4  0x00007fffe5a01360 in llvm::ShuffleVectorInst::ShuffleVectorInst (this=0x7fffa01f06f8, V1=0x7fffa0010278, V2=0x7fffa000eab8, Mask=0x7fffa00fe4e0, 
    Name=..., InsertBefore=0x0) at /home/0/LLVM_git/60/lib/IR/Instructions.cpp:1802
1802    assert(isValidOperands(V1, V2, Mask) &&
(gdb) call V1->dump()
  %43 = load <2 x i64>, <2 x i64>* %42, align 128
(gdb) call V2->dump()
  %47 = load <2 x i64>, <2 x i64>* %46, align 128
(gdb) call Mask->dump()
<4 x i32> <i32 0, i32 1, i32 4, i32 5>


#5  0x00007fffecf15b30 in llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>::CreateShuffleVector (Name=..., Mask=0x7fffa00fe4e0, 
    V2=0x7fffa000eab8, V1=0x7fffa0010278, this=0x7fffdaff9c80) at /home/0/LLVM_git/60/include/llvm/IR/IRBuilder.h:1746
1746      return Insert(new ShuffleVectorInst(V1, V2, Mask), Name);
(gdb) 

#6  llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>::CreateShuffleVector (Name=..., IntMask=..., V2=0x7fffa000eab8, 
    V1=0x7fffa0010278, this=0x7fffdaff9c80) at /home/0/LLVM_git/60/include/llvm/IR/IRBuilder.h:1752
1752      return CreateShuffleVector(V1, V2, Mask, Name);
(gdb) 

#7  (anonymous namespace)::X86InterleavedAccessGroup::transpose_4x4 (Matrix=..., TransposedMatrix=..., this=<optimized out>)
    at /home/0/LLVM_git/60/lib/Target/X86/X86InterleavedAccess.cpp:694
694   Value *IntrVec1 = Builder.CreateShuffleVector(Matrix[0], Matrix[2], Mask);
```

this seems like an LLVM bug.

**Comment by franz** [comment]
LLVM 5 still passes both tests.

**Comment by franz** [comment]
LLVM bug: https://bugs.llvm.org/show_bug.cgi?id=37616
