### ISSUE TITLE
Result of "copyKernelFromBitcode" causes llvm segfault when writing bitcode

### ISSUE THREAD

**Issue by PeterTh** [pocl/pocl#638]
In particular, the segfault happens during the call to `WriteBitcodeToFile` in LLVMFileUtils line 396.
This occurs only when a bitcode file **contains more than one kernel**.

Removing
`copyKernelFromBitcode(kernel->name, parallel_bc, program_bc);`
and simply using 
`llvm::Module *parallel_bc = llvm::CloneModule(program_bc).release();`
to create `parallel_bc` fixes the issues and makes our unit tests using multiple kernels work without issues.

However, I haven't openend a pull request for this since I assume that the intended behavior of `copyKernelFromBitcode` (only copying the reachable functions) is desired for some reason (e.g. performance?).

**Comment by franz** [comment]
Yes, that is intended behaviour. parallel.bc should not contain more than one kernel, ever.

**Comment by PeterTh** [comment]
What I'm testing is the _most experimental_ setup I guess ;)
The problem occurs with 

- SPIR programs 
- containing multiple kernels 
- that are being mapped to PTX for CUDA execution. 

I'm actually pretty impressed with how well this rather convoluted setup works after the change described above.

**Comment by psalz** [comment]
If I may chime in here, I just confirmed that this problem still persists on the current git master of POCL (94fba9f).

Here's a simple SYCL/ComputeCpp program that crashes for me:
```c++
#include <iostream>

#include <CL/sycl.hpp>

int main(int argc, char** argv) {
    std::cout << "Running ComputeCpp " << COMPUTECPP_VERSION_MAJOR << "." 
              << COMPUTECPP_VERSION_MINOR << "." << COMPUTECPP_VERSION_PATCH
              << std::endl;

#ifdef _MSC_VER
    std::cout << "Running on Windows\n";
#else
    std::cout << "Running on Linux\n";
#endif

#ifdef NDEBUG
    std::cout << "Release build\n";
#else
    std::cout << "Debug build\n";
#endif

    try {
        cl::sycl::gpu_selector selector;
        cl::sycl::queue queue(selector,
            [](cl::sycl::exception_list el) { std::cout << "ASYNC ERROR\n"; }); 

        std::cout << "Running on "
                  << queue.get_device()
                         .get_platform()
                         .get_info<cl::sycl::info::platform::name>()
                  << queue.get_device()
                         .get_platform()
                         .get_info<cl::sycl::info::platform::version>()
                  << " / "
                  << queue.get_device().get_info<cl::sycl::info::device::name>()
                  << "\n";

        cl::sycl::buffer<float, 1> buf_a(32);

        queue.submit([&](cl::sycl::handler& cgh) {
            auto dw_a =
                buf_a.get_access<cl::sycl::access::mode::discard_write>(cgh);
            cgh.parallel_for<class some_kernel>(buf_a.get_range(),
                [=](cl::sycl::item<1> item) { dw_a[item] = 1.f; }); 
        });

        queue.submit([&](cl::sycl::handler& cgh) {
            auto rw_a =
                buf_a.get_access<cl::sycl::access::mode::read_write>(cgh);
            cgh.parallel_for<class some_other_kernel>(buf_a.get_range(),
                [=](cl::sycl::item<1> item) { rw_a[item] += 1.f; }); 
        });

        queue.wait_and_throw();

    } catch(cl::sycl::exception& ex) {
        std::cerr << ex.what() << std::endl;
        return EXIT_FAILURE;
    }   

    return EXIT_SUCCESS;
}
```

Most of it is logging of the execution environment, the important part is that *it contains more than one kernel*. If I remove the second kernel, everything works fine! Here's the output on my testing setup:

```
Running ComputeCpp 1.0.2
Running on Linux
Debug build
Running on Portable Computing LanguageOpenCL 1.2 pocl 1.3-pre/upstream-master-0-g94fba9f Release, LLVM 6.0.0, SPIR, SLEEF, CUDA, POCL_DEBUG / Tesla K20m
Segmentation fault (core dumped)
```

And the backtrace from the core dump:

```
#0  0x00007fcd3f521b93 in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1
#1  0x00007fcd3f529b8e in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1
#2  0x00007fcd3f52c0d1 in llvm::BitcodeWriter::writeModule(llvm::Module const*, bool, llvm::ModuleSummaryIndex const*, bool, std::array<unsigned int, 5ul>*) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1
#3  0x00007fcd3f52c1ff in llvm::WriteBitcodeToFile(llvm::Module const*, llvm::raw_ostream&, bool, llvm::ModuleSummaryIndex const*, bool, std::array<unsigned int, 5ul>*) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1
#4  0x00007fcd434592b3 in pocl_write_module () from /usr/local/lib/libpocl.so.2.3.0
#5  0x00007fcd434346e3 in pocl_cache_write_kernel_parallel_bc ()
   from /usr/local/lib/libpocl.so.2.3.0
#6  0x00007fcd4347f380 in pocl_llvm_generate_workgroup_function ()
   from /usr/local/lib/libpocl.so.2.3.0
#7  0x00007fcd4344377f in load_or_generate_kernel () from /usr/local/lib/libpocl.so.2.3.0
#8  0x00007fcd4341449c in program_compile_dynamic_wg_binaries ()
   from /usr/local/lib/libpocl.so.2.3.0
#9  0x00007fcd43416055 in compile_and_link_program ()
   from /usr/local/lib/libpocl.so.2.3.0
#10 0x00007fcd4341426e in POclBuildProgram () from /usr/local/lib/libpocl.so.2.3.0
#11 0x00007fcd5046271e in cl::sycl::detail::program::build_current_program(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
   from /software-local/ComputeCpp-CE-1.0.2-Ubuntu-16.04-x86_64/lib/libComputeCpp.so
```

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
