### ISSUE TITLE
clpeak fails on x86_64

### ISSUE THREAD

**Issue by fabiand** [pocl/pocl#72]
Hey,

because of the ml announcement of the andorid port I discovered clpeak. Sadly it fails on my desktop machine:
```
$ ./clpeak 

Platform: Portable Computing Language
  Device: pthread-Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
    Driver version  : 0.9 (Linux x64)
    Compute units   : 4
    Clock frequency : 3400 MHz

    Global memory bandwidth (GBPS)
      float   : 7.35
      float2  : 10.13
      float4  : 10.97
      float8  : 12.49
      float16 : 15.42

    Single-precision compute (GFLOPS)
      float   : 2.06
      float2  : 2.87
      float4  : 8.44
      float8  : 3.18
      float16 : 1.39

    Double-precision compute (GFLOPS)
      double   : 2.14
      double2  : 6.22
      double4  : 1.17
      double8  : Speicherzugriffsfehler (Speicherabzug geschrieben)
                       ^^ segfault


$ gdb ./clpeak
...
(gdb) bt
#0  0x00007ffff488d7db in _compute_dp_v8 () from /tmp/poclDH1p5F/pthread/compute_dp_v8/256-1-1.0-0-0/parallel.so
#1  0x00007ffff72ae47e in workgroup_thread () from /usr/lib64/libpocl.so.1.2.0
#2  0x00007ffff6c37c53 in start_thread (arg=0x7ffff549b700) at pthread_create.c:308
#3  0x0000003b08ef5dbd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
(gdb)
```

**Comment by pjaaskel** [comment]
Assuming fixed. Please reopen if not.
