### ISSUE TITLE
use of unknown builtin '__builtin_amdgcn_*'

### ISSUE THREAD

**Issue by KOLANICH** [pocl/pocl#795]
```
KOLANICH@KOLANICH:~$ python3 ./test.py 
Choose platform:
[0] <pyopencl.Platform 'Clover' at 0x7fb9f7d681e0>
[1] <pyopencl.Platform 'Portable Computing Language' at 0x7fb9a77ee680>
Choice [0]:1
Set the environment variable PYOPENCL_CTX='1' to avoid being asked again.
1 warning and 3 errors generated.
Traceback (most recent call last):
  File "./test.py", line 10, in <module>
    prg = cl.Program(ctx, (thisDir/"kernel.cl").read_text("utf-8")).build()
  File "/usr/local/lib/python3.7/dist-packages/pyopencl/__init__.py", line 510, in build
    options_bytes=options_bytes, source=self._source)
  File "/usr/local/lib/python3.7/dist-packages/pyopencl/__init__.py", line 554, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'pthread-AMD A10-9600P RADEON R5, 10 COMPUTE CORES 4C+6G' on 'Portable Computing Language' at 0x16c29e0>:

error: /home/KOLANICH/.cache/pocl/kcache/tempfile-56-8e-fb-56-16.cl:145:20: use of unknown builtin '__builtin_amdgcn_workgroup_id_x'
error: /home/KOLANICH/.cache/pocl/kcache/tempfile-56-8e-fb-56-16.cl:145:90: use of unknown builtin '__builtin_amdgcn_workitem_id_x'
error: /home/KOLANICH/.cache/pocl/kcache/tempfile-56-8e-fb-56-16.cl:145:151: use of unknown builtin '__builtin_amdgcn_implicitarg_ptr'
warning: /home/KOLANICH/.cache/pocl/kcache/tempfile-56-8e-fb-56-16.cl:145:126: cast to 'const __constant uint *' (aka 'const __constant unsigned int *') from smaller integer type 'int'

(options: -I /usr/local/lib/python3.7/dist-packages/pyopencl/cl)
(source saved as /tmp/tmpltqt11i1.cl)
```

the error is present in both pocl built with and without SPIR-V

**Comment by franz** [comment]
Pocl does not support AMD GPUs directly, and it never did. We only had limited support for AMD APUs via HSA backend. Besides you're compiling for the CPU part of the APU:

> pyopencl.Device 'pthread-AMD A10-9600P

**Comment by KOLANICH** [comment]
Yes, so I completely have no idea why anything related to GPU is involved.

**Comment by franz** [comment]
I would try to look at the source from the last line:
```
(source saved as /tmp/tmpltqt11i1.cl)
```
or ``test.py`` or the source in ``.cache/pocl/kcache/tempfile-<hash>.cl``; but anyway since the error comes from sources, i don't see how this could be a bug in pocl.

**Comment by KOLANICH** [comment]
My bad. I have been experimenting with compiling OpenCL kernels with clang++, it had some issues with `get_global_id` (it was unavailable IDK why), so I had replaced it with the intrinsics specific for the card and have forgotten about it. When compiled with pocl, of course, everything has failed.
